name: Genshin Codes to Telegram

on:
  schedule:
    - cron: '0 10 * * *' # Roda todo dia às 10h (ou o horário que você configurou)
  workflow_dispatch: # Permite rodar manualmente no botão "Run workflow"

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código fonte
        uses: actions/checkout@v4
        
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Instalar dependências necessárias
        run: pip install httpx
        
      - name: Executar Script de Resgate
        run: python redeem_codes.py
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
